- name: Install httpd
  yum: pkg=httpd state=latest

- name: Change httpd port to listen on 8080
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
  notify: restart httpd

- name: create a site available directory
  file: path=/etc/httpd/sites-available state=directory owner=root mode=0755

- name: create a site enabled directory
  file: path=/etc/httpd/sites-enabled state=directory owner=root mode=0755

- name: create a wordpress virtual host file
  template: src=virtualhost.conf dest=/etc/httpd/sites-available/wordpress.conf

- name: make a symbolic link to sites-enabled
  file: src=/etc/httpd/sites-available/wordpress.conf dest=/etc/httpd/sites-enabled/wordpress.conf owner=root mode=0755 state=link

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify: restart httpd

- name: Insert site available to the httpd configuration file
  lineinfile: dest=/etc/httpd/conf/httpd.conf line="IncludeOptional sites-enabled/*.conf" state=present
  notify: restart httpd

- name: start and enable httpd
  service: name=httpd state=started enabled=yes

- name: install php
  yum: pkg=php state=latest 
  
- name: install php-myql
  yum: pkg=php-mysql state=latest
