- name: Install xfsprogs
  yum: pkg=xfsprogs state=present

- name: create a xfs filesystem on /dev/sdb
  filesystem: fstype=xfs dev=/dev/sdb

- name: create mount point on server 1 and server 2
  file: path=/data/glusterfs/var-www/{{ brick }} state=directory owner=root mode=0755

- name: edit fstab and mount the volume
  mount: path=/data/glusterfs/var-www/{{ brick }} src=/dev/sdb fstype=xfs state=mounted  

- name: install glusterd on both servers
  yum: pkg=centos-release-gluster state=present

- name: install glusterfs
  yum: pkg=glusterfs-server state=present

- name: change ownership of data-gluster
  file: path=/data/glusterfs/var-www/ owner=apache group=apache

- name: start glusterfs
  service: name=glusterd state=started enabled=yes

- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- name: probe glusterfs nodes
  shell: "gluster peer probe {{ item }}"
  with_items:
    - "192.168.56.105"
    - "192.168.56.106"


- name: Configure Gluster volume.
  shell: "gluster volume create var-www replica 2 transport tcp 192.168.56.105:/data/glusterfs/var-www/brick01/brick 192.168.56.106:/data/glusterfs/var-www/brick02/brick force"
  register: gluster_volume_create
  changed_when: "'successful' in gluster_volume_create.stdout"
  when: "inventory_hostname == groups.websrv[0] and 'Volume Name: var-www' not in gluster_volume_info.stdout"

- name: move old var www directory to a different location
  command: mv /var/www /var/www.orig

- name: create new var www directory
  file: path=/var/www/html state=directory owner=root mode=0755

- name: mount var www directory
  mount: path=/var/www src={{ ip_address }}:/var-www fstype=glusterfs opts="defaults,_netdev,fetch-attempts=5 0 0" state=mounted
  
- name: start gluster volume
  shell: gluster volume start var-www
  register: gluster_volume_start
  changed_when: "'successful' in gluster_volume_start.stdout"
  when: "inventory_hostname == groups.websrv[0] and 'Volume Name: var-www' not in gluster_volume_info.stdout"

