- name: Install Keepalived server
  yum: pkg=keepalived state=latest

- name: Install the configuration of keepalived
  template: src=templates/keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: Start keepalived
  service: name=keepalived state=started

